name: Action
description: Test
inputs:
 user_name:
   description: "Name"
   required: true

outputs:
 Out:
   description: "Testing O/P"
 
runs:
 using: "composite"
 steps:
 - runs: |
    chmod 777 ./entrypoint.sh
    $GITHUB_ACTION_PATH/entrypoint.sh ${{input.user_name}}
   shell: bash
  
