#name: Action
#description: Test
#inputs:
# user_name:
#   description: "Name"
#   required: true

#outputs:
# Out:
#   description: "Testing O/P"
 
#runs:
# using: "composite"
# steps:
# - runs: |
#    chmod 777 ./entrypoint.sh
#    $GITHUB_ACTION_PATH/entrypoint.sh ${{input.user_name}}
#   shell: bash
name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
 Out:
   description: "Testing"
   
runs:
  using: "composite"
  steps:
    - run: chmod 777 ./entrypoint.sh
      shell: bash
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
#    - id: random-number-generator
#      run: echo "::set-output name=random-id::$(echo $RANDOM)"
#      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash  
