on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: gala
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.gala.outputs.Out }}
        shell: bash
