# This is a basic workflow to help you get started with Actions

name: BasicPL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 build:
    runs-on: ubuntu-latest
    steps:
      ##Checkout## 
      - name: Checkout repo on Branch Master
        uses: actions/checkout@v2
      ##Setup JDK##
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      ##Build with maven##
      - name: Build with Maven
        run: mvn clean install --batch-mode --update-snapshots verify
      ##List files##
      - name: Listing files and present working directory
        run: |
          ls -ltr
          pwd
      ##Publishing artifact##
      - name: Upload Build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Jar File
          path: target/*.jar 
      ##Code Quality Check##
 SonarCloud:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: SonarCloud Scan
       run: mvn -B sonar:sonar -Dsonar.projectKey=SamreenKhanumF_simple-java-maven-app -Dsonar.projectName=simple-java-maven-app -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c9ba03744770a9974227d0441a920bb67cdfdb51
       #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SamreenKhanumF_simple-java-maven-app
       #uses: sonarsource/sonarcloud-github-action@master
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        ##Curl##
 Curl:
  runs-on: ubuntu-latest
  needs: SonarCloud
  steps:
   - name: curl
     run: curl -XGET -d 'Bugs' 'https://sonarcloud.io/organizations/samreenkhanumf/projects'
#Deploy-Dev:
 #   runs-on: ubuntu-latest
 #   needs: SonarCloud
 #   steps:
 #   - name: Status
 #    run: echo ${{ job.status }}
 
 #       uses: actions/cache@v1
 #       with:
 #         path: ~/.sonar/cache
 #         key: ${{ runner.os }}-sonar
 #         restore-keys: ${{ runner.os }}-sonar
 #     - name: Cache Maven packages
 #       uses: actions/cache@v1
 #       with:
 #         path: ~/.m2
 #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
 #         restore-keys: ${{ runner.os }}-m2
 #     - name: Build and analyze
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
 #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 #       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SamreenKhanumF_simple-java-maven-app      
